# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_storysurvey_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storysurvey',
            old_name='public',
            new_name='is_public',
        ),
    ]
