# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20160402_1107'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='storysurvey',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='storysurvey',
            name='end',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storysurvey',
            name='start',
            field=models.TextField(blank=True),
        ),
    ]
