# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorySurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'The title of the survey.', max_length=90)),
            ],
        ),
    ]
