# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysurvey',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Determines if the survey is public for users to take.'),
        ),
    ]
