# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20160404_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorySurvey',
            new_name='Story',
        ),
    ]
